services:
  - type: web
    name: desicrafts-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
      python backend/manage.py migrate
    startCommand: gunicorn backend.my_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.my_project.settings
      - key: STRIPE_SECRET_KEY
        value: (put value in dashboard)
      - key: STRIPE_PUBLISHABLE_KEY
        value: (put value in dashboard)

  - type: web
    name: desicrafts-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
